# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mdlib/md.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emdlib/md.proto\x12\tprotoblog\"k\n\x08\x44\x42\x41\x63tion\x12\'\n\x0b\x61\x63tion_type\x18\x01 \x01(\x0e\x32\x12.protoblog.Actions\x12\x10\n\x03key\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05value\x18\x03 \x01(\tH\x01\x88\x01\x01\x42\x06\n\x04_keyB\x08\n\x06_value\"\xe5\x01\n\x08InitConn\x12/\n\x0b\x61\x63tion_type\x18\x01 \x01(\x0e\x32\x1a.protoblog.InitConnActions\x12\x14\n\x07\x64\x62_name\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x16\n\tclient_id\x18\x03 \x01(\x05H\x01\x88\x01\x01\x12\x14\n\x07\x64\x62_hash\x18\x04 \x01(\tH\x02\x88\x01\x01\x12\x14\n\x07\x64\x62_file\x18\x05 \x01(\x0cH\x03\x88\x01\x01\x12\x12\n\x05state\x18\x06 \x01(\x08H\x04\x88\x01\x01\x42\n\n\x08_db_nameB\x0c\n\n_client_idB\n\n\x08_db_hashB\n\n\x08_db_fileB\x08\n\x06_state*j\n\x07\x41\x63tions\x12\x0c\n\x08\x41\x44\x44_ITEM\x10\x00\x12\r\n\tSET_VALUE\x10\x01\x12\x11\n\rGET_KEY_VALUE\x10\x02\x12\x10\n\x0cGET_ALL_KEYS\x10\x03\x12\x0e\n\nDELETE_KEY\x10\x04\x12\r\n\tDELETE_DB\x10\x05*\x81\x01\n\x0fInitConnActions\x12\x0c\n\x08\x41\x44\x44_USER\x10\x00\x12\x13\n\x0f\x41\x44\x44_PERMISSIONS\x10\x01\x12\x0b\n\x07\x44\x42_INFO\x10\x02\x12\x11\n\rCHECK_DB_HASH\x10\x03\x12\x10\n\x0cGET_DB_STATE\x10\x04\x12\n\n\x06GET_DB\x10\x05\x12\r\n\tINIT_DONE\x10\x06\x62\x06proto3')

_ACTIONS = DESCRIPTOR.enum_types_by_name['Actions']
Actions = enum_type_wrapper.EnumTypeWrapper(_ACTIONS)
_INITCONNACTIONS = DESCRIPTOR.enum_types_by_name['InitConnActions']
InitConnActions = enum_type_wrapper.EnumTypeWrapper(_INITCONNACTIONS)
ADD_ITEM = 0
SET_VALUE = 1
GET_KEY_VALUE = 2
GET_ALL_KEYS = 3
DELETE_KEY = 4
DELETE_DB = 5
ADD_USER = 0
ADD_PERMISSIONS = 1
DB_INFO = 2
CHECK_DB_HASH = 3
GET_DB_STATE = 4
GET_DB = 5
INIT_DONE = 6


_DBACTION = DESCRIPTOR.message_types_by_name['DBAction']
_INITCONN = DESCRIPTOR.message_types_by_name['InitConn']
DBAction = _reflection.GeneratedProtocolMessageType('DBAction', (_message.Message,), {
  'DESCRIPTOR' : _DBACTION,
  '__module__' : 'mdlib.md_pb2'
  # @@protoc_insertion_point(class_scope:protoblog.DBAction)
  })
_sym_db.RegisterMessage(DBAction)

InitConn = _reflection.GeneratedProtocolMessageType('InitConn', (_message.Message,), {
  'DESCRIPTOR' : _INITCONN,
  '__module__' : 'mdlib.md_pb2'
  # @@protoc_insertion_point(class_scope:protoblog.InitConn)
  })
_sym_db.RegisterMessage(InitConn)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACTIONS._serialized_start=370
  _ACTIONS._serialized_end=476
  _INITCONNACTIONS._serialized_start=479
  _INITCONNACTIONS._serialized_end=608
  _DBACTION._serialized_start=29
  _DBACTION._serialized_end=136
  _INITCONN._serialized_start=139
  _INITCONN._serialized_end=368
# @@protoc_insertion_point(module_scope)
